// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcW1VzJTR0vK-hhVMLIzURaxVdc9bn_w',
    appId: '1:663927605279:web:2b9c4c53377dd5fa642d2a',
    messagingSenderId: '663927605279',
    projectId: 'smart-farm-app-17a42',
    authDomain: 'smart-farm-app-17a42.firebaseapp.com',
    databaseURL: 'https://smart-farm-app-17a42-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-app-17a42.firebasestorage.app',
    measurementId: 'G-82C05295WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbZUU3ZYg-ZEWcqf-oGXpRKe4PKobLaZ4',
    appId: '1:663927605279:android:030ded790e609ea8642d2a',
    messagingSenderId: '663927605279',
    projectId: 'smart-farm-app-17a42',
    databaseURL: 'https://smart-farm-app-17a42-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-app-17a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhZoyDlaAWK_TqLagcWcPeMZ7Bznyyv8',
    appId: '1:663927605279:ios:b2c1a1790a3f3353642d2a',
    messagingSenderId: '663927605279',
    projectId: 'smart-farm-app-17a42',
    databaseURL: 'https://smart-farm-app-17a42-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-app-17a42.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhZoyDlaAWK_TqLagcWcPeMZ7Bznyyv8',
    appId: '1:663927605279:ios:b2c1a1790a3f3353642d2a',
    messagingSenderId: '663927605279',
    projectId: 'smart-farm-app-17a42',
    databaseURL: 'https://smart-farm-app-17a42-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-app-17a42.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjcW1VzJTR0vK-hhVMLIzURaxVdc9bn_w',
    appId: '1:663927605279:web:931f7b83753988fb642d2a',
    messagingSenderId: '663927605279',
    projectId: 'smart-farm-app-17a42',
    authDomain: 'smart-farm-app-17a42.firebaseapp.com',
    databaseURL: 'https://smart-farm-app-17a42-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-app-17a42.firebasestorage.app',
    measurementId: 'G-2JXJPRDZDJ',
  );
}
